---
browser: firefox
host: http://qa.ndb.capvision.com/
#tags: home,consultant,client
# tags:
   # home: true
   # consultant: true
   # client: true
   # contact: true
   # compliance: true
   # Con_R: true
   # international: true
   # invoicing: true
   # payment: true
   # profile: true
   # conference: true
   # consultation: true
   # convey: true
   # HR: true
   # report: true
   # test: false
tags:
   home: false
   consultant: false
   client: false
   contact: false
   compliance: false
   Con_R: false
   international: false
   invoicing: false
   payment: false
   profile: false
   conference: false
   consultation: false
   convey: false
   HR: false
   report: false
   test: true
